Add more softwares
LeStegii/server-softwares pull request #61
Opened 2023-09-17 14:24 UTC by TonimatasDEV

I have added a new category for software that technically are not server softwares (libraries...)

Close #48 
Close #45 

**Added:**
- minestom-ce
- native-minecraft-server
- Craft
- infrated

2023-09-17 16:24 UTC, TonimatasDEV commented
@LeStegii I will not add any more to this pull request, when you have time, correct it and add the emojis.

2023-09-17 19:32 UTC, LeStegii requested changes
Thank you very much for your pull request, there are so many servers I can 100% relate to you not being able to find fitting emojies.

I have a few requests though, mainly related to paid softwares.

2023-09-17 19:32 UTC, LeStegii commented on java/MODS.md
> +### [⬛ ModLoaderMP](https://mcarchive.net/mods/modloadermp)
I tried to get some information about ModLoaderMP, it seems to be a fork of Risugamis Modloader, which itself seems to be a very old loader.

https://ftb.fandom.com/wiki/ModLoaderMP
http://www.minecraftforum.net/topic/86765-166-sdks-mods-v5-more-bug-fixes/

So I guess it would be a fork of Risugami, which we could add if we find some more information.

2023-09-17 19:32 UTC, LeStegii commented on java/OTHER.md
> +- **Plugins:** -
Not entirely sure about adding another "OTHER" category as we already got one. Maybe we could merge both or split them into more detailed sub categories.

2023-09-17 19:32 UTC, LeStegii commented on java/PLUGINS.md
> +### [⬛ Dionysus](https://github.com/nopjmp/Dionysus)
I don't think this is inactive as the last commit was only two months ago.

2023-09-17 19:32 UTC, LeStegii commented on java/PROXIES.md
> +
Please remove all paid resources.

2023-09-17 19:32 UTC, LeStegii commented on java/PROXIES.md
> +- **Description:** GuardHexa is a premium fork of HexaCord that patches a lot of bugs/exploits and has a bit of optimization.
Please remove all paid resources.

2023-09-17 21:30 UTC, TonimatasDEV commented on java/PROXIES.md
> +
> Please remove all paid resources.

Done

2023-09-17 21:30 UTC, TonimatasDEV commented on java/PROXIES.md
> +- **Description:** GuardHexa is a premium fork of HexaCord that patches a lot of bugs/exploits and has a bit of optimization.
> Please remove all paid resources.

Done

2023-09-17 21:32 UTC, TonimatasDEV commented on java/PLUGINS.md
> +### [⬛ Dionysus](https://github.com/nopjmp/Dionysus)
Done

2023-09-17 21:41 UTC, TonimatasDEV commented on java/MODS.md
> +### [⬛ ModLoaderMP](https://mcarchive.net/mods/modloadermp)
Done

2023-09-17 21:45 UTC, TonimatasDEV commented
> Thank you very much for your pull request, there are so many servers I can 100% relate to you not being able to find fitting emojies.
> 
> I have a few requests though, mainly related to paid softwares.

All ready, we will have to put the logos of the server softwares.

2023-09-17 21:50 UTC, TonimatasDEV commented on java/MODS.md
> +### [⬛ ModLoaderMP](https://mcarchive.net/mods/modloadermp)
> I tried to get some information about ModLoaderMP, it seems to be a fork of Risugamis Modloader, which itself seems to be a very old loader.
> 
> https://ftb.fandom.com/wiki/ModLoaderMP http://www.minecraftforum.net/topic/86765-166-sdks-mods-v5-more-bug-fixes/
> 
> So I guess it would be a fork of Risugami, which we could add if we find some more information.

Done

2023-09-18 05:56 UTC, LeStegii approved these changes
LGTM!
I will refactor some of the softwares into a BUKKIT and NONBUKKIT (not the final name) category because right now, the PLUGINS category isn't detailed enough imo.

2023-09-18 05:56 UTC, merged