Add more softwares
LeStegii/server-softwares pull request #65
Opened 2023-11-19 18:29 UTC by TonimatasDEV

- [ ] Add 20 softwares

Added softwares:
1. Granite
2. GoLandMc
3. Graphene
4. Hematite
5. EnchiladaSpigot

Updated softwares:
- Magma

2023-11-20 08:17 UTC, LeStegii requested changes
Thank you for the contribution! I Have some small notes and ideas ^^

2023-11-20 08:17 UTC, LeStegii commented on java/PLUGINS.md
> +
I don't think this is a fork worth listing. It seems to just be an old state of the repository with the readme changed. There are no releases and no changes to the code except an old PR that never got merged.
![grafik](https://github.com/LeStegii/server-softwares/assets/50475262/919150cc-74f1-481f-8362-1ca1ee7baa50)

2023-11-20 08:17 UTC, LeStegii commented on java/VANILLA.md
> +- **Description:** Graphene is a server software created, from scratch, by the same developer as
The description seems to be incomplete.

2023-11-20 08:17 UTC, LeStegii commented on java/PLUGINS.md
> +- **Version:** -
This fork seems to be for 1.16.3 (see [here](https://github.com/duplexsystem/Hydrinity/blob/master/patches/api/0001-POM-Changes.patch#L25))

2023-11-20 08:17 UTC, LeStegii commented on java/PLUGINS.md
> +
This would require us to reorder the list a bit, but should we move this into the FOLIA section? Maybe we could rename the section to something more general like multi-server.

2023-11-20 09:01 UTC, TonimatasDEV commented on java/PLUGINS.md
> +
Folia and MultiPaper are different I think, one is for making a server that contains many mini servers and folia is a multi-core server that loads regions by cores.

2023-11-20 09:32 UTC, LeStegii commented on java/PLUGINS.md
> +
Yea, you're right, it's not really the same.

2023-11-20 09:32 UTC, LeStegii commented on java/PLUGINS.md
> +
It's made for the same audience though.

2023-11-20 10:08 UTC, TonimatasDEV commented on java/PLUGINS.md
> +
> It's made for the same audience though.

I add it to the "OTHER" category temporarily?

2023-11-20 10:28 UTC, LeStegii commented on java/PLUGINS.md
> +
Nah, it's ok for now. I will add the icons later, then I'll merge it

2023-11-20 10:41 UTC, TonimatasDEV commented on java/PLUGINS.md
> +
Perfect

2023-12-07 07:16 UTC, LeStegii commented
Thanks! Haven't found the time to add icons yet, but I will do it asap!

2023-12-24 10:14 UTC, merged