Fix all issues and add more softwares
LeStegii/server-softwares pull request #78
Opened 2024-02-12 15:50 UTC by TonimatasDEV

Fixes #77 
Fixes #76 
Fixes #75 
Fixes #73 

And add more softwares of #24 
- PaperMC-unpatch
- PaperBin
- Origami
- Lantern
- PartyCraft
- OpenSandbox

2024-02-12 16:32 UTC, TonimatasDEV commented
@LeStegii Finished

2024-02-13 20:39 UTC, TonimatasDEV commented
Fixes #79

2024-02-16 08:35 UTC, LeStegii requested changes

2024-02-16 08:35 UTC, LeStegii commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
Fork chain got messed up here.

2024-02-16 08:35 UTC, LeStegii commented on java/PLUGINS.md
> +- **Plugins:** Reflx
Does this fit into this category then?

2024-02-16 08:35 UTC, LeStegii commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
The link is incorrect.

2024-02-16 08:35 UTC, LeStegii commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
I think we should change the description to be a bit more informative.

2024-02-16 08:35 UTC, LeStegii commented on java/VANILLA.md
> +- **Description:** Open source, multithreaded, voxel game engine and platform, written in Java.
If I remember correctly, spout had bukkit support.

2024-02-16 15:15 UTC, TonimatasDEV commented on java/PLUGINS.md
> +- **Plugins:** Reflx
I think yes. It has a plugin system

2024-02-16 15:15 UTC, TonimatasDEV commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
Fixed

2024-02-16 15:15 UTC, TonimatasDEV commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
Fixed.

2024-02-16 15:17 UTC, TonimatasDEV commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
Done

2024-02-29 17:14 UTC, TonimatasDEV commented
@LeStegii

2024-02-29 19:58 UTC, merged

2024-02-29 19:58 UTC, LeStegii commented
Thanks for the mention!