Softwares to software and some other changes
LeStegii/server-softwares pull request #95
Opened 2024-06-30 21:43 UTC by TonimatasDEV

2024-06-30 23:14 UTC, TonimatasDEV commented
@LeStegii Done. When you have time, check it.

2024-07-01 11:35 UTC, LeStegii requested changes

2024-07-01 11:35 UTC, LeStegii commented on OTHERS.md
> +This list contains software that are related to minecraft servers but are no servers or proxies.
Shouldn't this be "[...] software which is related to [...] but isn't server or proxy related." or something like this?

2024-07-01 11:35 UTC, LeStegii commented on RECOMMEND.md
> +**Note:** Some software are outdated and are no longer being actively developed. They may still be useful, but they aren't supported and most likely contain security vulnerabilities, like Log4Shell,
"are" would have to be changed to "is"

2024-07-01 11:35 UTC, LeStegii commented on RECOMMEND.md
> +- Create a pure Minecraft experience without modifications, opt for the [Vanilla](bedrock/VANILLA.md#-vanilla) server.
The grammar seems to be wrong here

2024-07-01 11:35 UTC, LeStegii commented on RECOMMEND.md
> +- Connect multiple Java Edition servers using [Velocity](java/PROXIES.md#-velocity) or [Bungeecord](java/PROXIES.md#-bungeecord).
I don't know if we should recommend bungeecord.

2024-07-01 11:35 UTC, LeStegii commented on bedrock/PLUGINS.md
> +Since most of the software do not support all vanilla features, it's recommended to use [GeyserMC](/OTHERS.md#-geysermc) (Bedrock to Java Bridge) instead if you want to play vanilla.
"do" would have to be changed to "does"

2024-07-01 11:35 UTC, LeStegii commented on bedrock/VANILLA.md
> +### [🌍 Vanilla](https://www.minecraft.net/en-us/download/server/bedrock)
I think "Bedrock Dedicated Server" should stay

2024-07-01 11:35 UTC, LeStegii commented on java/LOST.md
> +- **Author:** ?
I think this has been made by md_5

2024-07-01 11:35 UTC, LeStegii commented on java/MODS+PLUGINS.md
> -### [🧻 Cardboard (Bukkit for Fabric)](https://www.curseforge.com/minecraft/mc-mods/cardboard)
The official curseforge name still includes "Spigot for Fabric" so we could include this as well

2024-07-01 11:35 UTC, LeStegii commented on java/PLUGINS.md
> +
As this doesn't supprt plugins, why is it in the plugins category?

2024-07-01 11:37 UTC, LeStegii commented on java/PLUGINS.md
> +
Also, from what I can see, the ci links to a github repository which we should link instead

2024-07-01 13:58 UTC, TonimatasDEV commented on java/MODS+PLUGINS.md
> -### [🧻 Cardboard (Bukkit for Fabric)](https://www.curseforge.com/minecraft/mc-mods/cardboard)
In GitHub, the logo and the slug are only Cardboard

2024-07-01 14:02 UTC, TonimatasDEV commented on java/PLUGINS.md
> +
> As this doesn't supprt plugins, why is it in the plugins category?

Yes it supports.
https://ci.codecrafter47.de/job/Rainbow/org.projectrainbow$PluginExample/

2024-07-01 14:08 UTC, TonimatasDEV commented
Done!

2024-07-04 18:50 UTC, lunofe commented on java/LOST.md
AnchorMC might just have moved, looks like the original author: https://github.com/PassTheMayo/AnchorMC

2024-07-04 18:52 UTC, lunofe requested changes
AnchorMC might just have moved, looks like the original author: https://github.com/PassTheMayo/AnchorMC

2024-07-04 18:53 UTC, LeStegii commented
> AnchorMC might just have moved, looks like the original author: https://github.com/PassTheMayo/AnchorMC

Good catch!

2024-07-04 19:29 UTC, lunofe commented
One more thing; should the _lost_ category actually be a Java exclusive, instead of a general one, just like _others_?

https://github.com/LeStegii/server-softwares/blob/949aabc3e4f53f4669d96aac8b29c017968ed962/java/LOST.md?plain=1#L1-L2

2024-07-04 19:31 UTC, LeStegii commented
> One more thing; should the _lost_ category actually be a Java exclusive, instead of a general one, just like _others_?
> 
> https://github.com/LeStegii/server-softwares/blob/949aabc3e4f53f4669d96aac8b29c017968ed962/java/LOST.md?plain=1#L1-L2

It depends. It would make sense to split java and bedrock lost softwares.

2024-07-04 19:36 UTC, lunofe commented
But is it? I feel like if it's lost, you don't really need a separation because you're most likely just checking the category to learn some trivia,

2024-07-04 19:39 UTC, LeStegii commented
> But is it? I feel like if it's lost, you don't really need a separation because you're most likely just checking the category to learn some trivia,

Maybe we could add something like `- Type: Bedrock/Java/Other` than

2024-07-04 22:24 UTC, TonimatasDEV commented
Done! Moved LOST to general and update AnchorMC

2024-07-04 22:28 UTC, TonimatasDEV commented
I added Thunderbolt now.

2024-07-11 06:21 UTC, LeStegii commented
@lunofe Could you hit me up when the gh pages are ready so that I can merge this PR?

2024-07-11 16:24 UTC, lunofe commented
@LeStegii can be merged 👍🏻

2024-07-12 21:41 UTC, LeStegii approved these changes

2024-07-12 21:43 UTC, merged